# bundle exec jekyll serve

# Site settings
title: Digital Collecting Toolkit
email: digital_collecting@virginia.edu
description: "Digital Collecting Toolkit, written by the University of Virginia Library"
baseurl: "/toolkit" # the subpath of your site, e.g. /blog
url: "http://digitalcollecting.lib.virginia.edu" # the base hostname & protocol for your site, e.g. http://example.com

permalink: pretty
exclude: ["node_modules/", "*.gemspec", "*.gem", "Gemfile", "Gemfile.lock", "package.json", "package-lock.json",  "script/", "LICENSE.txt", "lib/", "bin/", "README.md", "Rakefile"]

sass:
  sass_dir: _sass
  style: condensed

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Enable or disable the site search // comment out line below to disable:
search_enabled: true

# Google Analytics Tracking (optional)
# e.g, UA-1234567-89 // uncomment line below to enable:
# ga_tracking: